[project]
name = "oil-spill-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pyproj>=3.8.0",
    "rasterio>=1.5.1",
    "scipy>=1.18.1",
    "streamlit>=1.63.0",
    "torch>=2.14.0",
]
